export const ADD_GAME = 'ADD_GAME';
export const SHOW_ALL_GAMES = 'SHOW_ALL_GAMES';
export const SHOW_GAME_DETAIL = 'SHOW_GAME_DETAIL';
export const EDIT_GAME = 'EDIT_GAME';
export const DELETE_GAME = 'DELETE_GAME';
export const GAME_ERROR = 'GAME_ERROR';

export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const ADMIN_AUTH_ERROR = 'ADMIN_AUTH_ERROR';
export const SHOW_ALL_USERS = 'SHOW_ALL_USERS';
export const SHOW_USERS_ERROR = 'SHOW_USERS_ERROR';
export const DELETE_USER_REVIEW = 'DELETE_USER_REVIEW';
export const DELETE_USER_ACCOUNT = 'DELETE_USER_ACCOUNT';
