// game
export const ADD_GAME = 'ADD_GAME';
export const SHOW_ALL_GAMES = 'SHOW_ALL_GAMES';
export const SHOW_GAME_DETAIL = 'SHOW_GAME_DETAIL';
export const EDIT_GAME = 'EDIT_GAME';
export const DELETE_GAME = 'DELETE_GAME';
export const GAME_ERROR = 'GAME_ERROR';

// admin
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const ADMIN_AUTH_ERROR = 'ADMIN_AUTH_ERROR';
export const SHOW_ALL_USERS = 'SHOW_ALL_USERS';
export const SHOW_USER_DETAIL = 'SHOW_USER_DETAIL';
export const SHOW_USER_REVIEWS = 'SHOW_USER_REVIEWS';
export const SHOW_USERS_ERROR = 'SHOW_USERS_ERROR';
export const DELETE_USER_REVIEW = 'DELETE_USER_REVIEW';
export const DELETE_USER_ACCOUNT = 'DELETE_USER_ACCOUNT';

// auth
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const DELETE_USER_PROFILE = 'DELETE_USER_PROFILE';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';

// alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// game reviews
export const ADD_GAME_REVIEW = 'ADD_GAME_REVIEW';
export const SHOW_ALL_REVIEWS = 'SHOW_ALL_REVIEWS';
export const SHOW_ALL_GAME_REVIEWS = 'SHOW_ALL_GAME_REVIEWS';
export const SHOW_AVERAGE_RATING = 'SHOW_AVERAGE_RATING';
export const GAME_REVIEW_DETAIL = 'GAME_REVIEW_DETAIL';
export const EDIT_GAME_REVIEW = 'EDIT_GAME_REVIEW';
export const DELETE_GAME_REVIEW = 'DELETE_GAME_REVIEW';
export const GAME_REVIEW_ERROR = 'GAME_REVIEW_ERROR';

// profile
export const SHOW_ALL_PROFILES = 'SHOW_ALL_PROFILES';
export const USER_REVIEWS = 'USER_REVIEWS';
export const TERMINATE_USER_REVIEW = 'TERMINATE_USER_REVIEW';
export const PROFILE_ERROR = 'PROFILE_ERROR';
